version: '3.9'

services:
  pgdb:
    image: postgres:14-alpine
    container_name: base_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./base_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zahid
      - POSTGRES_USER=zahid
      - POSTGRES_DB=base_db 

  adminer:
    image: adminer:latest
    container_name: adminer_viewer
    restart: always
    ports:
      - 8080:8080